import fs from 'fs'
import path from 'path'

import { faker } from '@faker-js/faker'
import { db } from 'api/src/lib/db.js'
import { parse } from 'csv-parse/sync'

// Manually apply seeds via the `yarn cedar prisma db seed` command.
// See https://cedarjs.com/docs/database-seeds for more info
//
// INFERRED DATA SEEDING:
// - Set USE_INFERRED_DATA to true to seed from parsed rates data CSV files
// - These files are generated by the parseRatesData mutation in the rates service
// - Files are automatically selected by most recent timestamp
// - When enabled, seeds MeasurementUnits, Services, and Rates with synchronized IDs
// - Rates require at least one user in the database to use as author

// ============================================================================
// SEED CONFIGURATION
// ============================================================================
// Control which data types are seeded. Set force to true to always reseed,
// or false to only seed if the table is empty.
// Override via environment: FORCE_SEED_MEASUREMENT_UNITS=true yarn cedar prisma db seed

// Set to true to use inferred CSV files from parseRatesData
// Set to false to use original CSV files
const USE_INFERRED_DATA = false

const seedConfig = {
  fakeUsers: {
    enabled: false,
    force: false, // Set to true to always reseed fakeUsers
  },
  measurementUnits: {
    enabled: true,
    force: false, // Set to true to always reseed measurement units
  },
  services: {
    enabled: true,
    force: false,
  },
  rates: {
    enabled: true,
    force: false,
  },
} as const

// ============================================================================
// SEED FUNCTIONS
// ============================================================================

const seedFakeUsers = async () => {
  const count = 10

  for (let i = 0; i < count; i++) {
    const name = faker.person.fullName()
    const email = faker.internet.email().toLowerCase()

    await db.user.upsert({
      where: { email },
      update: {},
      create: {
        email,
        name,
      },
    })
  }

  return count
}

const seedMeasurementUnits = async () => {
  // Determine which CSV file to use based on configuration
  let csvPath: string
  if (USE_INFERRED_DATA) {
    // Find the most recent inferred measurement units file
    const dataDir = path.resolve('./scripts/data')
    const files = fs
      .readdirSync(dataDir)
      .filter((f) =>
        f.match(/\d{4}-\d{2}-\d{2}-inferred-measurement-units\.csv/)
      )
      .sort()
      .reverse()

    if (files.length > 0) {
      csvPath = path.join(dataDir, files[0])
      console.info(`  Using inferred data: ${files[0]}`)
    } else {
      console.info('  No inferred measurement units file found, using original')
      csvPath = path.resolve(
        './scripts/data/20240628-export-measurement-units.csv'
      )
    }
  } else {
    csvPath = path.resolve(
      './scripts/data/20240628-export-measurement-units.csv'
    )
  }

  if (!fs.existsSync(csvPath)) {
    console.info('Skipping MeasurementUnit seed: CSV file not found')
    return 0
  }

  try {
    const csvContent = fs.readFileSync(csvPath, 'utf-8')
    const records = parse(csvContent, {
      columns: true,
      skip_empty_lines: true,
    }) as Array<Record<string, string>>

    let seeded = 0
    for (const record of records) {
      await db.measurementUnit.upsert({
        where: { id: parseInt(record.id) },
        update: {},
        create: {
          id: parseInt(record.id),
          fullName: record.fullName,
          pluralName: record.pluralName || record.fullName,
          shortName: record.shortName || null,
          symbol: record.symbol || null,
          notation: record.notation || null,
          dimension: (record.dimension || 'CUSTOM') as any, // Enum value
          description: record.description || null,
          conversionFactor: record.conversionFactor
            ? parseFloat(record.conversionFactor)
            : null,
          baseUnit: record.baseUnit || null,
        },
      })
      seeded++
    }

    // Reset the auto-increment sequence to avoid ID conflicts
    await db.$executeRawUnsafe(`
      SELECT setval(
        pg_get_serial_sequence('"MeasurementUnit"', 'id'),
        COALESCE((SELECT MAX(id) FROM "MeasurementUnit"), 1),
        true
      );
    `)

    return seeded
  } catch (error) {
    console.error('Error seeding MeasurementUnit:', error)
    return 0
  }
}

const seedServices = async () => {
  // Determine which CSV file to use based on configuration
  let csvPath: string
  if (USE_INFERRED_DATA) {
    // Find the most recent inferred services file
    const dataDir = path.resolve('./scripts/data')
    const files = fs
      .readdirSync(dataDir)
      .filter((f) => f.match(/\d{4}-\d{2}-\d{2}-inferred-services\.csv/))
      .sort()
      .reverse()

    if (files.length > 0) {
      csvPath = path.join(dataDir, files[0])
      console.info(`  Using inferred data: ${files[0]}`)
    } else {
      console.info('  No inferred services file found, using fallback')
      csvPath = path.resolve('./scripts/data/inferred_services.csv')
    }
  } else {
    csvPath = path.resolve('./scripts/data/inferred_services.csv')
  }

  if (!fs.existsSync(csvPath)) {
    console.info('Skipping Service seed: CSV file not found')
    return 0
  }

  try {
    const csvContent = fs.readFileSync(csvPath, 'utf-8')
    const records = parse(csvContent, {
      columns: true,
      skip_empty_lines: true,
    }) as Array<Record<string, string>>

    let seeded = 0
    for (const record of records) {
      // For inferred data with IDs, use upsert; otherwise find by unique fields
      if (record.id && USE_INFERRED_DATA) {
        await db.service.upsert({
          where: { id: parseInt(record.id) },
          update: {},
          create: {
            id: parseInt(record.id),
            action: record.action as any,
            material: record.material || '',
            context: record.context || null,
            description: record.description || null,
          },
        })
        seeded++
      } else {
        const where = {
          action: record.action as any,
          material: record.material || '',
          description: record.description || '',
        }

        const exists = await db.service.findFirst({ where })
        if (exists && !seedConfig.services?.force) {
          continue
        }

        if (!exists) {
          await db.service.create({
            data: {
              action: record.action as any,
              material: record.material || '',
              context: record.context || null,
              description: record.description || null,
            },
          })
          seeded++
        }
      }
    }

    // Reset the auto-increment sequence if using inferred data with IDs
    if (USE_INFERRED_DATA) {
      await db.$executeRawUnsafe(`
        SELECT setval(
          pg_get_serial_sequence('"Service"', 'id'),
          COALESCE((SELECT MAX(id) FROM "Service"), 1),
          true
        );
      `)
    }

    return seeded
  } catch (error) {
    console.error('Error seeding Service:', error)
    return 0
  }
}

const seedRates = async () => {
  if (!USE_INFERRED_DATA) {
    console.info('  Rates seeding only available with inferred data')
    return 0
  }

  // Find the most recent inferred rates file
  const dataDir = path.resolve('./scripts/data')
  const files = fs
    .readdirSync(dataDir)
    .filter((f) => f.match(/\d{4}-\d{2}-\d{2}-inferred-rates\.csv/))
    .sort()
    .reverse()

  if (files.length === 0) {
    console.info('  No inferred rates file found')
    return 0
  }

  const csvPath = path.join(dataDir, files[0])
  console.info(`  Using inferred data: ${files[0]}`)

  if (!fs.existsSync(csvPath)) {
    console.info('Skipping Rate seed: CSV file not found')
    return 0
  }

  try {
    // Get the first user to use as author
    const firstUser = await db.user.findFirst()
    if (!firstUser) {
      console.info(
        '  Skipping Rate seed: No users found (required for authorId)'
      )
      return 0
    }

    const csvContent = fs.readFileSync(csvPath, 'utf-8')
    const records = parse(csvContent, {
      columns: true,
      skip_empty_lines: true,
    }) as Array<Record<string, string>>

    let seeded = 0
    for (const record of records) {
      const serviceId = parseInt(record.serviceId)
      const unitId = parseInt(record.unitId)
      const subAmount = parseFloat(record.subAmount) || 0
      const retailAmount = parseFloat(record.retailAmount) || 0

      // Check if service and unit exist
      const serviceExists = await db.service.findUnique({
        where: { id: serviceId },
      })
      const unitExists = await db.measurementUnit.findUnique({
        where: { id: unitId },
      })

      if (!serviceExists || !unitExists) {
        console.warn(
          `  Skipping rate: service ${serviceId} or unit ${unitId} not found`
        )
        continue
      }

      // Check for unique constraint: authorId + serviceId + unitId
      const where = {
        authorId_serviceId_unitId: {
          authorId: firstUser.id,
          serviceId,
          unitId,
        },
      }

      const exists = await db.rate.findUnique({ where })
      if (exists && !seedConfig.rates?.force) {
        continue
      }

      if (exists) {
        await db.rate.update({
          where,
          data: {
            subAmount,
            retailAmount,
            currency: 'USD',
            description: record.description || null,
          },
        })
      } else {
        await db.rate.create({
          data: {
            serviceId,
            unitId,
            subAmount,
            retailAmount,
            currency: 'USD',
            authorId: firstUser.id,
            description: record.description || null,
          },
        })
        seeded++
      }
    }

    return seeded
  } catch (error) {
    console.error('Error seeding Rate:', error)
    return 0
  }
}

// ============================================================================
// SEED REGISTRY
// ============================================================================
// Maps config keys to their seed functions and checks for existing data

type SeedFunction = () => Promise<number>

const seedRegistry: Record<
  keyof typeof seedConfig,
  {
    fn: SeedFunction
    check: () => Promise<boolean> // Returns true if data already exists
  }
> = {
  fakeUsers: {
    fn: seedFakeUsers,
    check: () => db.user.findFirst().then((u) => !!u),
  },
  measurementUnits: {
    fn: seedMeasurementUnits,
    check: () => db.measurementUnit.findFirst().then((u) => !!u),
  },
  services: {
    fn: seedServices,
    check: () => db.service.findFirst().then((u) => !!u),
  },
  rates: {
    fn: seedRates,
    check: () => db.rate.findFirst().then((r) => !!r),
  },
}

// ============================================================================
// MAIN SEED EXECUTION
// ============================================================================

export default async () => {
  try {
    console.info('Starting database seed...\n')

    for (const [key, config] of Object.entries(seedConfig)) {
      if (!config.enabled) {
        console.info(`⊘ Skipping ${key} (disabled in config)`)
        continue
      }

      const registryEntry = seedRegistry[key as keyof typeof seedConfig]
      if (!registryEntry) {
        console.warn(`⚠ No seed function found for ${key}`)
        continue
      }

      // Check if data already exists
      const dataExists = await registryEntry.check()
      const shouldSeed = config.force || !dataExists

      if (!shouldSeed) {
        console.info(`⊘ Skipping ${key} (data already exists)`)
        continue
      }

      try {
        const count = await registryEntry.fn()
        console.info(`✓ Seeded ${count} ${key}`)
      } catch (error) {
        console.error(`✗ Error seeding ${key}:`, error)
      }
    }

    console.info('\n✓ Database seed complete')
  } catch (error) {
    console.error('Fatal error during seed:', error)
  } finally {
    await db.$disconnect()
  }
}
